<?php

/**
 * @file
 * Module hooks for du_policies module.
 */

use Drupal\views\Views;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function du_policies_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__policy' => [
      'base hook' => 'paragraph',
    ],
    'node__policy' => [
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
// function du_policies_views_pre_render(ViewExecutable $view) {
//   if (isset($view) && ($view->storage->id()=='policy')) {
//     $view->element['#attached']['library'][] = 'du_policies/policy';
//   }
// }

/**
 * Implements hook_preprocess_HOOK() for node--policy.
 */
function du_policies_preprocess_node__policy(&$variables) {
  // Attach the policy library to the policy node.
  $variables['#attached']['library'][] = 'du_policies/policy';
}

function du_policies_preprocess_paragraph__policy(&$variables) {
  $args = [];

  // Check if a specific policy state field is set by the paragraph.
  $tids = $variables['paragraph']->get('field_policy_state')->getValue();
  if ($tids) {
    $args[] = implode(',', array_column($tids, 'target_id'));
  }
  else {
    $args[] = 'all';
  }

  $view = Views::getView('policy');
  $render_array = $view->buildRenderable('block_1', $args);
  $variables['policy'] = $render_array;

  $variables['#attached']['library'][] = 'du_policies/policy';
}