<?php

/**
 * @file
 * Module hooks for du_policies module.
 */

use Drupal\views\Views;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function du_policies_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__policy' => [
      'base hook' => 'paragraph',
    ],
    // 'node__policy' => [
    //   'base hook' => 'node',
    // ], // currently viewing an indivual node is breaking outside of pl_drupal
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function du_policies_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id()=='policy')) {
    $view->element['#attached']['library'][] = 'du_policies/policy';
  }
}

function du_policies_preprocess_paragraph__policy(&$variables) {
  $args = [];

  // Check if a specific policy state field is set by the paragraph.
  $values = $variables['paragraph']->get('field_policy_state')->getValue();
  if ($values) {
    $args[] = implode(',', array_column($values, 'value'));
  } else {
    $args[] = 'all';
  }

  $view = Views::getView('policy');
  $render_array = $view->buildRenderable('block_1', $args);
  $variables['policy'] = $render_array;
}